/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_msg (XDR *xdrs, msg *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (4 +  5 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cmd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->status, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->type);
			IXDR_PUT_LONG(buf, objp->cmd);
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
			{
				register int *genp;

				for (i = 0, genp = objp->status;
					i < 5; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (4 +  5 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cmd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->status, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->type = IXDR_GET_LONG(buf);
			objp->cmd = IXDR_GET_LONG(buf);
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->status;
					i < 5; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cmd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->status, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
